// Generated by the hunt editor (editor.html). Answers are stored as salted hashes.
window.HUNT = {
  "version": 1,
  "salt": "rona-hunt-7f3k2q",
  "title": "Rona's Curious Kitchen",
  "subtitle": "A puzzle hunt, made with love",
  "mascot": "👩‍🍳",
  "intro": "Welcome, chef! 🍳\n\nThe **Grand Kitchen Contest** is tonight, and the judges want proof you've got what it takes. Each chapter is a course: solve its puzzles, then crack the **meta** that ties them together.\n\nAnswers are words or short phrases. Spaces, capitals and punctuation don't matter.\n\n*(This is a sample hunt. Open the editor to make it your own!)*",
  "ending": "You did it! The judges are speechless. 🏆\n\nDinner is served... and it's for two. ❤️",
  "settings": {
    "chapterUnlock": "all"
  },
  "images": {},
  "chapters": [
    {
      "id": "c-demo1",
      "title": "Starters",
      "subtitle": "Something to whet the appetite",
      "icon": "🥗",
      "color": "#e4572e",
      "intro": "Four little bites. Each answer is an ingredient.",
      "metaUnlock": "all",
      "puzzles": [
        {
          "id": "p-demo1",
          "title": "Pantry Shuffle",
          "icon": "🧂",
          "flavor": "Someone knocked the label maker over...",
          "body": "Unscramble the jar label:\n\n```\nT L A S\n```",
          "partials": [],
          "hints": [
            "It is on every table, usually next to the pepper."
          ],
          "solveText": "",
          "answerHashes": [
            "04e0360830c36eac835fe877c33320bf50d4cbb703c325f1c46d49d3e2e5e174"
          ]
        },
        {
          "id": "p-demo2",
          "title": "Pit Stop",
          "icon": "🫒",
          "flavor": "Green or black, never orange.",
          "body": "I grow on a tree, I'm pressed into gold,\nI'm stuffed with pimento, I'm briny, I'm old.\nWhat am I?",
          "partials": [
            {
              "message": "Close! Just the fruit, please.",
              "hash": "49a16810abce576dc45542864853800123c96916eb440475a2e927314c577b92"
            }
          ],
          "hints": [],
          "solveText": "",
          "answerHashes": [
            "1b704f1c739e556e591fc965bf6ad254d3a87ec729e43ba804d24a04e66551af"
          ]
        },
        {
          "id": "p-demo3",
          "title": "The Fifth Taste",
          "icon": "🍜",
          "flavor": "Sweet, sour, salty, bitter, and...?",
          "body": "| Taste | Example |\n|---|---|\n| Sweet | Honey |\n| Sour | Lemon |\n| Salty | Pretzel |\n| Bitter | Coffee |\n| **?** | Parmesan, soy sauce, mushrooms |",
          "partials": [
            {
              "message": "Right idea! What is the Japanese word for it?",
              "hash": "09c16a032a3c531acb0865c0e9770a88935c4c5ae4401bda75c9e329f0b53620"
            },
            {
              "message": "Right idea! What is the Japanese word for it?",
              "hash": "1a6f797bcb32e81a5be829a20d7b8f13f940abd74965eab1dc5334af7a842af3"
            }
          ],
          "hints": [
            "The word comes from Japanese.",
            "It starts with U."
          ],
          "solveText": "",
          "answerHashes": [
            "6cf57b00094719124ea6c117b3d2d3462f50e9b51df31f1abdecf5d42a5a2f54"
          ]
        },
        {
          "id": "p-demo4",
          "title": "Hot Stuff",
          "icon": "🌶️",
          "flavor": "Handle with care.",
          "body": "- Bell ___\n- Black ___\n- Dr ___\n- ___mint",
          "partials": [],
          "hints": [],
          "solveText": "",
          "answerHashes": [
            "673feb00121c5c2579ecf14d57a7f500faa2260879fa107e2423f6e93a7d5bbc"
          ]
        }
      ],
      "meta": {
        "id": "p-demo5",
        "title": "First Course",
        "icon": "🍲",
        "flavor": "What do all four starters make together?",
        "body": "Take the **first letter** of each Starters answer, in order.\n\nWhat would you serve first?",
        "partials": [],
        "hints": [],
        "solveText": "Soup's on! The judges look impressed.",
        "answerHashes": [
          "eef657a93df52dc6b84d5b083086191e057b8c853cd445093e65306594ffc49b"
        ]
      }
    },
    {
      "id": "c-demo2",
      "title": "Mains",
      "subtitle": "The heart of the meal",
      "icon": "🍝",
      "color": "#4f9d69",
      "intro": "Three hearty puzzles. The meta opens after any **two** of them.",
      "metaUnlock": 2,
      "puzzles": [
        {
          "id": "p-demo6",
          "title": "Licorice Bulb",
          "icon": "🌿",
          "flavor": "Tastes like anise, looks like celery.",
          "body": "F _ N N _ L",
          "partials": [],
          "hints": [],
          "solveText": "",
          "answerHashes": [
            "6306fcde32cbb264128224d290228ab83f429bef1ca4d3279e7031832adcb171"
          ]
        },
        {
          "id": "p-demo7",
          "title": "Pizza Herb",
          "icon": "🍕",
          "flavor": "Sprinkled on every slice.",
          "body": "Fill in the blank:\n\n> Basil, thyme, rosemary and ______ walk into a pizzeria...",
          "partials": [],
          "hints": [],
          "solveText": "",
          "answerHashes": [
            "c33d36e8415ba065ebb13668241bb7cbcdc91a45eec927cd7ab3b6e125c1e854",
            "939101db82b379d4c1d2ddecc5b4f28f3dda194c8e82c1a17cc047b5cd76cb6e"
          ]
        },
        {
          "id": "p-demo8",
          "title": "Grain of Truth",
          "icon": "🍚",
          "flavor": "Long, short, sticky, wild.",
          "body": "Sushi needs it. Risotto needs it. Paella needs it.",
          "partials": [],
          "hints": [],
          "solveText": "",
          "answerHashes": [
            "9ff132e23e41256c56c2c06531238774f6d58f1c8c3741a264beb631afa4398b"
          ]
        }
      ],
      "meta": {
        "id": "p-demo9",
        "title": "Second Course",
        "icon": "🍽️",
        "flavor": "A tiny word with a big heart.",
        "body": "First letters again!",
        "partials": [],
        "hints": [],
        "solveText": "",
        "answerHashes": [
          "8833f4b25e996b24ebb2c692b2bddbab6af11158c078f9850913ee8a0d0b1454"
        ]
      }
    }
  ],
  "finale": {
    "id": "p-finale",
    "title": "Dinner Is Served",
    "icon": "❤️",
    "flavor": "Bring it all together.",
    "body": "Write your two meta answers in order, then add the number of people at this table.",
    "partials": [],
    "hints": [],
    "solveText": "...and it is all for you. ❤️",
    "enabled": true,
    "answerHashes": [
      "ac2382af1ef8be5793a268ff62d3bd0d5a51cc06d8b8d3ea0a78f7b2f423dec2"
    ]
  }
};
